resources:
  containers:
  - container: arm64v8-test-container
    image: electronbuilds/arm64v8:0.0.5
    options: --shm-size 128m

jobs:
- job: Test_Arm64
  container: arm64v8-test-container
  displayName: Test Arm64 on Arm64 hardware
  timeoutInMinutes: 30
  steps:
  - template: vsts-arm-test-steps.yml
